version: '3'

services:
  app:
    build: .
    restart: always
    command: yarn start
    networks:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./tmp:/home/app/tmp
    environment:
      - NODE_ENV=production

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    networks:
      - mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${DB_DATABASE}

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./tmp/redis:/data
    networks:
      - redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

networks:
  mysql:
  redis:
