version: '3'

services:
  app:
    build: .
    restart: always
    command: yarn start
    networks:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=production

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    networks:
      - mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

  redis:
    image: redis:alpine
    volumes:
      - ./tmp/redis:/data
    networks:
      - redis
    ports:
      - '6379:6379'

networks:
  mysql:
  redis:
