version: '3'

services:
  app:
    build: .
    image: app:latest
    restart: always
    command: yarn dev
    networks:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development

  queues:
    image: app:latest
    restart: always
    command: yarn dev:queues
    networks:
      - mysql
      - redis
    depends_on:
      - app
    environment:
      - NODE_ENV=development

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    networks:
      - mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

  redis:
    image: redis:alpine
    volumes:
      - ./tmp/redis:/data
    networks:
      - redis
    ports:
      - '6379:6379'

networks:
  mysql:
  redis:
