version: '3'

services:
  app:
    build: .
    restart: always
    tty: true
    networks:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    ports:
      - '3333:3333'
    volumes:
      - '.:/home/node/app'
      - /home/node/app/node_modules
    environment:
      NODE_ENV: development
      START_COMMAND: yarn dev

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - './tmp/mysql:/var/lib/mysql'
    networks:
      - mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

  redis:
    image: redis:alpine
    networks:
      - redis
    ports:
      - '6379:6379'

networks:
  mysql:
    driver: bridge
  redis:
    driver: bridge
