version: '3'

services:
  app:
    build: .
    restart: always
    command: yarn start
    networks:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    ports:
      - 3000:${PORT}
    environment:
      - NODE_ENV=production

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    networks:
      - mysql
    ports:
      - '3306:${DB_PORT}'
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
      - MYSQL_DATABASE=${DB_DATABASE}

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./tmp/redis:/data
    networks:
      - redis
    ports:
      - 6379:${REDIS_PORT}

networks:
  mysql:
  redis:
